# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master
- dev/*

pool:
  vmImage: 'macos-latest'

jobs:

- template: cicd/templates/build-android.yml
  parameters:
    project: 'OpenDuo-Android'
    name: 'OpenDuoAndroid'

- template: cicd/templates/build-ios.yml
  parameters:
    displayName: 'OpenDuoiOS'
    workingDirectory: 'OpenDuo-iOS'
    scheme: 'OpenDuo'
