# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenDuo' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  pod 'AgoraRtcEngine_iOS', '~> 3.5.1'
  pod 'AgoraRtm_iOS', '~> 1.4.8'
  
end
